// mindarc-assessment/components/card.vue
<template>
  <v-card class="mx-auto pt-1">
    <v-img class="white--text align-end ma-4" :src="cardData.image">
      <v-card-title>{{ cardData.title }}</v-card-title>
    </v-img>

    <v-card-text class="text-center">
      <h3 class="font-weight-regular">{{ cardData.content }}</h3>
    </v-card-text>

    <v-card-actions class="d-flex justify-center">
      <v-btn rounded outlined class="mb-5 text--Capitalize">{{
        cardData.linkText
      }}</v-btn>
    </v-card-actions>
  </v-card>
</template>

<script>
export default {
  props: {
    cardData: Object,
  },
}
</script>

// exercise-1/src/components/Card.jsx
export function Card({ image, title, description, buttonStyle, buttonLabel, buttonUrl }) {
  return (
    <div className="card h-100 text-center">
      {image && <img src={image} className="card-img-top rounded" alt={title} />}
      <div className="card-body h-100 d-flex flex-column align-items-center pb-0">
        {title && <h5 className="card-title">{title}</h5>}
        {description && <p className="card-text">{description}</p>}
        {buttonLabel && (
          <a href={buttonUrl} className={`btn btn-${buttonStyle} mt-auto`}>
            {buttonLabel}
          </a>
        )}
      </div>
    </div>
  )
}
