// src/components/Hero.vue
<script setup>
// import WelcomeItem from './WelcomeItem.vue'

</script>

<template>
  <div id="hero-section" class="hero-section container-fluid d-flex justify-content-center align-items-center vh-100">
    <div class="container-fluid h-100">
      <div class="row h-100 justify-content-center">
        <div class="col-12 d-flex justify-content-center align-items-center">
          <div class="content text-center">
            <h1 class="fs-1 text-white">Hello Developer!</h1>
            <p class="text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
#hero-section {
  background: url(@/assets/images/1920x650.png) no-repeat center center;
  background-size: cover;
  font-size: 32px;
}
</style>

// frontend-assessment/src/sectionComponents/Hero.jsx
import { useEffect, useState } from 'react';
import DesktopBanner from '../assets/images/desktopBanner.png';
import MobileBanner from '../assets/images/mobileBanner.png';

const HeroSection = () => {
    const [bannerImage, setBannerImage] = useState(DesktopBanner);

    useEffect(() => {
        const updateBannerImage = () => {
            if (window.innerWidth < 600) {
                setBannerImage(MobileBanner);
            } else {
                setBannerImage(DesktopBanner);
            }
        };

        updateBannerImage();
        window.addEventListener('resize', updateBannerImage);

        return () => {
            window.removeEventListener('resize', updateBannerImage);
        };
    }, []);

    return (  
    <>
        <section 
            className="relative h-[600px] md:h-[650px] flex items-center justify-center bg-cover bg-center" 
            style={{ backgroundImage: `url(${bannerImage})` }}
        >
            <div className="text-center">
                <h1 className="text-white text-4xl md:text-5xl lg:text-6xl font-bold">
                    Hello Developer!
                </h1>
                <p className="text-white mt-4 text-lg md:text-xl">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit
                </p>
            </div>
        </section>
    </>
    );
}
 
export default HeroSection;
