// exercise/src/components/exercise1/Header.vue
<template>
    <div class="header">
        <img class="header__img" :src="image"/>
        <div class="header__text--wrap">
            <p class="header__title">
                Hello Developer!
            </p>
            <p class="header__description">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>
        </div>
    </div>
</template>

<script lang="ts">
import {defineComponent, ref} from "vue";
import pinia from "@/stores/store.js";
import {useStore} from "@/stores/store";
const store = useStore(pinia)
export default defineComponent({
    name: "Header",
    setup() {
        const width : any = ref((window.innerWidth > 0) ? window.innerWidth : screen.width);
        const image = width.value > '480' ? ref('1920x650.png') : ref('600x600.png')
        return {
            width,
            image,
        }
    }
})
</script>

<style scoped>

</style>

// mindarc-frontend-assessment/src/components/header/header.tsx
import './header.css';

const Header = () => {
  return (
    <div className="header">
      <img className="header__image" src="https://via.placeholder.com/1920x650" />
      <div className="header__text">
        <h1 className="header__title">Hello Developer!</h1>
        <h3 className="header__subtitle">Lorem ipsum dolor sit amet, consectetur adipiscing elit</h3>
      </div>
    </div>
  );
};

export default Header;
