// src/components/Header.vue
<template>
  <div class="jumbotron jumbotron-fluid header header-text">
    <div class="container align-self-center">
      <h1 class="display-3">Hello Developer!</h1>
      <p class="h1">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import "../styles/base/media.scss";
@import "../styles/components/header.scss";
</style>

// mindarc-frontend-assessment/src/components/header/header.tsx
import './header.css';

const Header = () => {
  return (
    <div className="header">
      <img className="header__image" src="https://via.placeholder.com/1920x650" />
      <div className="header__text">
        <h1 className="header__title">Hello Developer!</h1>
        <h3 className="header__subtitle">Lorem ipsum dolor sit amet, consectetur adipiscing elit</h3>
      </div>
    </div>
  );
};

export default Header;
