// src/components/Hero.vue
<script setup>
// import WelcomeItem from './WelcomeItem.vue'

</script>

<template>
  <div id="hero-section" class="hero-section container-fluid d-flex justify-content-center align-items-center vh-100">
    <div class="container-fluid h-100">
      <div class="row h-100 justify-content-center">
        <div class="col-12 d-flex justify-content-center align-items-center">
          <div class="content text-center">
            <h1 class="fs-1 text-white">Hello Developer!</h1>
            <p class="text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
#hero-section {
  background: url(@/assets/images/1920x650.png) no-repeat center center;
  background-size: cover;
  font-size: 32px;
}
</style>

// web/src/components/Hero.tsx
import React from "react";

export const Hero: React.FC = () => (
  // Load separate placeholder images based on screen size
  <section className="relative h-screen md:h-[650px] text-white overflow-hidden">
    {/* TODO: DRY */}
    <img
      src="https://via.placeholder.com/1920x650"
      alt="Hero placeholder"
      className="hidden md:block absolute inset-0 w-full h-full object-cover"
    />
    <img
      src="https://via.placeholder.com/600x600"
      alt="Hero placeholder"
      className="md:hidden absolute inset-0 w-full h-full object-cover"
    />
    <div>
      <div className="text-center">
        <h1 className="text-5xl md:text-7xl font-bold mb-4">
          Hello Developer!
        </h1>
        <p className="text-xl md:text-2xl font-light tracking-wide">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit
        </p>
      </div>
    </div>
  </section>
);
